// Generated by scripts/snapshotPreF18.ts before the preparation-model migration.
// Every authored body each food resolved to beforehand. Do not edit by hand.

export const preF18Resolution: Record<string, Record<string, string[]>> = {
  "breakfast-cereals": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Breads and cereals: Cereals — Breakfast cereals, rice, pasta, and similar",
      "scope:Applies to breakfast cereals, rice, pasta and similar cereal foods.",
      "summary:The guide lists this food as okay to eat."
    ],
    "vegetarian-suitability": []
  },
  "rice": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Breads and cereals: Cereals — Breakfast cereals, rice, pasta, and similar",
      "scope:Applies to breakfast cereals, rice, pasta and similar cereal foods.",
      "summary:The guide lists this food as okay to eat."
    ],
    "vegetarian-suitability": []
  },
  "pasta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Breads and cereals: Cereals — Breakfast cereals, rice, pasta, and similar",
      "scope:Applies to breakfast cereals, rice, pasta and similar cereal foods.",
      "summary:The guide lists this food as okay to eat."
    ],
    "vegetarian-suitability": []
  },
  "fresh-filled-pasta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Breads and cereals: Cereals",
      "condition:composition|Do not treat the general pasta advice as applying to fresh filled pasta.",
      "scenario:When preparing or serving this food|Follow the advice specific to the filling.",
      "summary:Check the guidance for the filling before eating fresh filled pasta."
    ],
    "vegetarian-suitability": []
  },
  "brie": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "camembert": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "blue-cheese": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "ricotta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "mozzarella": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "feta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "halloumi": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "paneer": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Low acid soft pasteurised cheese",
      "condition:preparation|Do not eat it uncooked.",
      "scenario:When preparing or serving this food|Cook thoroughly before eating.",
      "scope:Applies to all low-acid soft pasteurised cheese.",
      "summary:Eat low-acid soft pasteurised cheese only when it is cooked."
    ],
    "vegetarian-suitability": []
  },
  "cheddar": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Hard cheese",
      "scope:Applies to all hard cheese.",
      "summary:The guide lists hard cheese as okay to eat when refrigerated."
    ],
    "vegetarian-suitability": [
      "scope:Applies to all hard cheese.",
      "summary:Traditional hard cheese can be set using animal-derived rennet, so check the label."
    ]
  },
  "parmesan": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Hard cheese",
      "scope:Applies to all hard cheese.",
      "summary:The guide lists hard cheese as okay to eat when refrigerated."
    ],
    "vegetarian-suitability": [
      "summary:Traditional Parmesan uses animal-derived rennet."
    ]
  },
  "gouda": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Hard cheese",
      "scope:Applies to all hard cheese.",
      "summary:The guide lists hard cheese as okay to eat when refrigerated."
    ],
    "vegetarian-suitability": [
      "scope:Applies to all hard cheese.",
      "summary:Traditional hard cheese can be set using animal-derived rennet, so check the label."
    ]
  },
  "cottage-cheese": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Pasteurised cottage cheese, cream cheese, etc",
      "condition:preparation|Alternatively, cook it before the package best-before date.",
      "condition:storage|Keep in its sealed pack and eat cold within two days of opening.",
      "scenario:When preparing or serving this food|Follow the sealed-pack, refrigeration, and use-by guidance.",
      "scope:Applies to pasteurised cottage cheese, cream cheese and similar pasteurised cheese.",
      "summary:Use pasteurised cheese from sealed packs within two days of opening, or cook it before its best-before date."
    ],
    "vegetarian-suitability": []
  },
  "cream-cheese": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Dairy: Cheese — Pasteurised cottage cheese, cream cheese, etc",
      "condition:preparation|Alternatively, cook it before the package best-before date.",
      "condition:storage|Keep in its sealed pack and eat cold within two days of opening.",
      "scenario:When preparing or serving this food|Follow the sealed-pack, refrigeration, and use-by guidance.",
      "scope:Applies to pasteurised cottage cheese, cream cheese and similar pasteurised cheese.",
      "summary:Use pasteurised cheese from sealed packs within two days of opening, or cook it before its best-before date."
    ],
    "vegetarian-suitability": []
  },
  "bluff-and-pacific-oysters": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood footnote: Bluff and Pacific oysters and queen scallops",
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood: Freshly cooked fish, mussels, oysters, crayfish, scallops, etc",
      "condition:frequency|Have no more than one serving per month.",
      "condition:preparation|Cook above 75°C throughout.",
      "scenario:When preparing or serving this food|Cook thoroughly and serve while hot.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "scope:Applies to all freshly cooked fish, mussels, oysters, crayfish and scallops.",
      "summary:Cook seafood thoroughly and eat it while hot.",
      "summary:Limit these shellfish to one serving each month."
    ],
    "vegetarian-suitability": []
  },
  "queen-scallops": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood footnote: Bluff and Pacific oysters and queen scallops",
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood: Freshly cooked fish, mussels, oysters, crayfish, scallops, etc",
      "condition:frequency|Have no more than one serving per month.",
      "condition:preparation|Cook above 75°C throughout.",
      "scenario:When preparing or serving this food|Cook thoroughly and serve while hot.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "scope:Applies to all freshly cooked fish, mussels, oysters, crayfish and scallops.",
      "summary:Cook seafood thoroughly and eat it while hot.",
      "summary:Limit these shellfish to one serving each month."
    ],
    "vegetarian-suitability": []
  },
  "seed-sprouts": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Miscellaneous: Sprouts and enoki mushrooms",
      "condition:preparation|Do not eat raw.",
      "scenario:When preparing or serving this food|Cook before eating.",
      "scope:Applies to all seed sprouts and enoki mushrooms.",
      "summary:Do not eat these raw; cook them first."
    ],
    "vegetarian-suitability": []
  },
  "enoki-mushrooms": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Miscellaneous: Sprouts and enoki mushrooms",
      "condition:preparation|Do not eat raw.",
      "scenario:When preparing or serving this food|Cook before eating.",
      "scope:Applies to all seed sprouts and enoki mushrooms.",
      "summary:Do not eat these raw; cook them first."
    ],
    "vegetarian-suitability": []
  },
  "gummy-bears": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Gummy bears can contain gelatin; gelatin-free alternatives exist."
    ]
  },
  "jelly": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Check whether jelly contains animal-derived ingredients; vegan alternatives exist."
    ]
  },
  "marshmallows": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Marshmallows traditionally contain animal-derived gelatin."
    ]
  },
  "starburst": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:The article identifies Starburst as containing gelatin."
    ]
  },
  "gelatin": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Gelatin is an animal-derived gelling ingredient."
    ]
  },
  "white-sugar": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:White sugar can be refined using bone char, so check how it is processed."
    ]
  },
  "vegetable-soup": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Restaurant vegetable soup can contain chicken broth, so ask about the ingredients."
    ]
  },
  "pies-and-other-pastries": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Some pies and other pastries use lard, so check the ingredients."
    ]
  },
  "wine-and-beer": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Some wines and beers use fish-derived isinglass; vegetarian alternatives exist."
    ]
  },
  "orange-juice": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Some orange juice brands add omega-3 derived from fish."
    ]
  },
  "tortillas": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Breads and cereals: Breads",
      "scope:Applies to all breads.",
      "summary:The guide lists this food as okay to eat."
    ],
    "vegetarian-suitability": [
      "summary:Some tortillas use lard, so check the ingredients or ask the cook."
    ]
  },
  "worcestershire-sauce": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Miscellaneous: Sauces, dressings and spreads",
      "condition:storage|Refrigerate opened products and observe the stated storage limit.",
      "scenario:When preparing or serving this food|Follow the manufacturer’s instructions after opening.",
      "scope:Applies to commercially manufactured sauces, dressings and spreads.",
      "summary:Refrigerate opened products and follow their manufacturer storage and heating instructions."
    ],
    "vegetarian-suitability": [
      "summary:Worcestershire sauce can contain anchovies; vegan alternatives exist."
    ]
  },
  "french-fries": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": [
      "summary:Restaurant fries can be cooked in animal fats, so ask how they are prepared."
    ]
  },
  "mayonnaise": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "hollandaise-sauce": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "caesar-dressing": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "mousse": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "tiramisu": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "panna-cotta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "condition:composition|Do not eat it if it contains raw egg.",
      "condition:preparation|If the egg in it is cooked, follow the guide’s cooked eggs advice instead.",
      "scenario:When preparing or serving this food|Check whether the food contains raw egg before eating it.",
      "scope:Applies to all cold desserts, because only some of them contain raw egg.",
      "summary:The guide says not to eat foods containing raw eggs, so check whether this one contains raw egg."
    ],
    "vegetarian-suitability": [
      "summary:Panna cotta traditionally uses gelatin to set."
    ]
  },
  "eggnog": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "egg-flips": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "summary:The guide names this among the foods containing raw eggs that it says not to eat."
    ],
    "vegetarian-suitability": []
  },
  "smoothies": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Eggs: Raw eggs",
      "condition:composition|Do not eat it if it contains raw egg.",
      "condition:preparation|If the egg in it is cooked, follow the guide’s cooked eggs advice instead.",
      "scenario:When preparing or serving this food|Check whether the food contains raw egg before eating it.",
      "scope:Applies to all home-made drinks, because only some of them contain raw egg.",
      "summary:The guide says not to eat foods containing raw eggs, so check whether this one contains raw egg."
    ],
    "vegetarian-suitability": []
  },
  "anchovy": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "arrow-squid": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "barracouta": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "blue-cod": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "brill-and-turbot": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "brown-trout": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "condition:other|Do not treat the listed excluded lake or geothermal source as unrestricted.",
      "scenario:When preparing or serving this food|Follow the source’s location exception.",
      "summary:The guide lists this trout as unrestricted only outside its stated excluded location."
    ],
    "vegetarian-suitability": []
  },
  "cockles": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "eel": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "elephant-fish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "flounders": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "gurnard": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "hoki": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "john-dory": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "ling": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "monkfish-or-stargazer": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "mussels": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood: Freshly cooked fish, mussels, oysters, crayfish, scallops, etc; Recommended fish servings",
      "condition:preparation|Cook above 75°C throughout.",
      "scenario:When preparing or serving this food|Cook thoroughly and serve while hot.",
      "summary:Cook thoroughly, eat while hot, and follow the source’s species-specific mercury notes."
    ],
    "vegetarian-suitability": []
  },
  "orange-perch": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "orange-roughy": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "oreo-dories": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "oysters": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood: Freshly cooked fish, mussels, oysters, crayfish, scallops, etc; Recommended fish servings",
      "condition:preparation|Cook above 75°C throughout.",
      "scenario:When preparing or serving this food|Cook thoroughly and serve while hot.",
      "summary:Cook thoroughly, eat while hot, and follow the source’s species-specific mercury notes."
    ],
    "vegetarian-suitability": []
  },
  "parore": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "scallops": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Seafood: Freshly cooked fish, mussels, oysters, crayfish, scallops, etc; Recommended fish servings",
      "condition:preparation|Cook above 75°C throughout.",
      "scenario:When preparing or serving this food|Cook thoroughly and serve while hot.",
      "summary:Cook thoroughly, eat while hot, and follow the source’s species-specific mercury notes."
    ],
    "vegetarian-suitability": []
  },
  "rainbow-trout": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "condition:other|Do not treat the listed excluded lake or geothermal source as unrestricted.",
      "scenario:When preparing or serving this food|Follow the source’s location exception.",
      "summary:The guide lists this trout as unrestricted only outside its stated excluded location."
    ],
    "vegetarian-suitability": []
  },
  "skipjack-tuna": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists skipjack tuna as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "yellowfin-tuna": {
    "pregnancy-food-safety": [],
    "vegetarian-suitability": []
  },
  "smooth-oreo": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "sole": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "southern-blue-whiting": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "surf-clams": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "tarakihi": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "toothfish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "warehou": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "whitebait": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: No restriction necessary",
      "summary:The guide lists this species as requiring no mercury-serving restriction."
    ],
    "vegetarian-suitability": []
  },
  "albacore-tuna": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "alfonsino": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "bass": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "bluenose": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "ghost-sharks": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "hake": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "hapuka-or-groper": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "javelin-fish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "kahawai": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "kingfish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "lake-taupo-trout": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "leatherjacket": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "lemon-sole": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "mackerel": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "red-cod": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "ribaldo": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "rig": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "rock-lobster": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "farmed-salmon": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "sea-perch": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "silverside": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "skate": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "snapper": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "sprats": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "trevally": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 3–4 servings per week acceptable",
      "condition:frequency|Have no more than three or four servings per week.",
      "scenario:When preparing or serving this food|Limit weekly intake.",
      "summary:Limit this species to three or four servings each week."
    ],
    "vegetarian-suitability": []
  },
  "cardinal-fish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "dogfish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "lake-rotomahana-trout": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "geothermal-lake-trout": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "school-shark": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "striped-marlin": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "southern-bluefin-tuna": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  },
  "swordfish": {
    "pregnancy-food-safety": [
      "citation:New Zealand Food Safety: Pullout guide to food safety in pregnancy|https://www.mpi.govt.nz/food-safety-home/food-pregnancy/list-safe-food-pregnancy|Recommended servings for fish species to minimise mercury intakes: 1 serving per 1–2 weeks acceptable",
      "condition:frequency|Have no more than one serving every one or two weeks.",
      "scenario:When preparing or serving this food|Limit intake during pregnancy.",
      "summary:Limit this species to one serving every one or two weeks."
    ],
    "vegetarian-suitability": []
  }
}
