import { writeFileSync } from 'node:fs'
import { contentIndex as index } from '../src/data'
import { resolveAssessment, type GuidanceLayer } from '../src/domain/assessment'

/**
 * Regenerates the preparation-migration wording snapshot. Run before moving any content:
 *   npx tsx scripts/snapshotPreF18.ts
 *
 * It records every authored body each food resolves to today, so the migration can be proven to
 * lose no wording. Bodies rather than statuses, because the migration deliberately re-scopes which
 * layer applies to which row while forbidding any change to what the layers say.
 */

const bodiesOf = (layers: GuidanceLayer[]): string[] => layers.flatMap((layer) => [
  ...(layer.assessment.summary === undefined ? [] : [`summary:${layer.assessment.summary}`]),
  ...(layer.assessment.scopeStatement === undefined ? [] : [`scope:${layer.assessment.scopeStatement}`]),
  ...layer.assessment.guidanceScenarios.flatMap((scenario) => [
    `scenario:${scenario.applicability}|${scenario.instruction}`,
    ...scenario.conditions.map((condition) => `condition:${condition.kind}|${condition.instruction}`),
  ]),
  ...layer.citations.map((citation) => `citation:${citation.title}|${citation.url}|${citation.locator}`),
])

const snapshot: Record<string, Record<string, string[]>> = {}
for (const food of index.foods) {
  const byList: Record<string, string[]> = {}
  for (const guidanceList of index.guidanceLists) {
    const resolved = resolveAssessment({ kind: 'food', food }, guidanceList, index)
    byList[guidanceList.id] = [...new Set(bodiesOf(resolved.layers))].sort()
  }
  snapshot[food.id] = byList
}

const banner = `// Generated by scripts/snapshotPreF18.ts before the preparation-model migration.
// Every authored body each food resolved to beforehand. Do not edit by hand.`

writeFileSync(
  'src/test/preF18Resolution.ts',
  `${banner}\n\nexport const preF18Resolution: Record<string, Record<string, string[]>> = ${JSON.stringify(snapshot, null, 2)}\n`,
)

console.log(`snapshot written for ${Object.keys(snapshot).length} foods`)
